version: '3.9'
services:
  mysql:
    build:
      context: ./services/mysql
      args:
        IMAGE: mysql:8.2
    image: mg-mysql:8.2
    container_name: mg-mysql8.2
    restart: always
    privileged: false
    volumes:
      - ./data/mysql8.2:/var/lib/mysql
      - ./conf/mysql:/docker-sql
    ports:
      - 33060:3306
    environment:
      TZ: ${TZ}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --lower_case_table_names=1
    networks: 
      - mgnet
  redis:
    build:
      context: ./services/redis
      args:
        IMAGE: redis:7.2
    image: mg-redis:7.2
    container_name: mg-redis7.2
    restart: always
    privileged: false
    volumes:
      - ./conf/redis/redis.conf:/etc/redis/redis.conf
      - ./data/redis:/data
      - ./logs/redis:/logs
    ports:
      - 63790:6379
    environment:
      - TZ:${TZ}
    command: redis-server /etc/redis/redis.conf --requirepass ${REDIS_PASSWORD}
    networks: 
      - mgnet
  php:
    build:
      context: ./services/php
      args:
        IMAGE: php:8.3-fpm
    image: mg-php:8.3
    container_name: mg-php8.3
    restart: always
    privileged: false
    volumes:
        - ./www:/www/
        - ./conf/php/php.ini/:/usr/local/etc/php/php.ini
        - ./logs/php:/var/log/php
    environment:
      - TZ:${TZ}
    depends_on:
      - redis
      - mysql
    networks: 
      - mgnet
  nginx:
    build:
      context: ./services/nginx
      args:
        IMAGE: nginx:1.25.3
    image: mg-nginx:1.25.3
    container_name: mg-nginx1.25.3
    restart: always
    privileged: false
    ports:
      - 9885:9885
    volumes:
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/nginx/conf.d:/etc/nginx/conf.d/
      - ./conf/nginx/ssl:/etc/nginx/ssl
      - ./logs/nginx:/var/log/nginx
      - ./www:/www/
    environment:
      - TZ:${TZ}
    depends_on:
      - php
    networks: 
      - mgnet
networks:
  mgnet:
    name: mgnet
    driver: bridge
    
